### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by lukeberry99** [killa-kyle/posture-posture-posture-chrome-extension#4]
What steps would be necessary to convert this to a Firefox extension?

I've not worked on extensions for either Firefox or Chrome, but I'm happy to pick it up if you think it's doable.

**Comment by killa-kyle** [comment]
Great question. I haven't done much looking into firefox yet, but came across this documentation:

https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

Chrome is going to force manifest V3 early next year in 2023 (the extension currently is using manifest v2), so it wouldn't hurt to look at releasing a firefox version in case I'm unable to update the extension to work with V3.

**Comment by killa-kyle** [comment]
I just attempted to submit the existing source code to firefox for publication. fingers crossed. If it makes it, it will be published at https://addons.mozilla.org/en-US/firefox/addon/posture-posture-posture/ eventually 

<img width="1407" alt="Screen Shot 2022-11-27 at 7 22 20 PM" src="https://user-images.githubusercontent.com/6319238/204168039-116e786d-013a-4791-8505-db37a01910d4.png">
